# Generated by Django 3.0.3 on 2020-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(default=1, max_length=32, verbose_name='Middle name'),
            preserve_default=False,
        ),
    ]
