# Generated by Django 3.0.3 on 2020-02-11 15:14

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200211_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=64, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='../static/images/avatar/women.jpg', upload_to='users/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_to_day',
            field=models.DateField(blank=True, null=True, verbose_name='User BirthDay'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=1, max_length=12, unique=True, validators=[account.models.validate_phone], verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.IntegerField(choices=[(1, 'administrator'), (2, 'master'), (3, 'manager')], default=2, verbose_name='Position in company'),
        ),
    ]
