# Generated by Django 3.0.3 on 2020-02-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200211_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('last_name',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
