# Generated by Django 3.0.3 on 2020-02-23 12:30

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200212_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Set office name', max_length=32, verbose_name='Office Name')),
                ('short_code', models.CharField(help_text='Set Short code for current office', max_length=5, verbose_name='Short Code')),
                ('address', models.TextField(blank=True, verbose_name='Place Affress Ofice')),
                ('twoGisCode', models.TextField(blank=True, help_text='Set 2gis code for curent place', verbose_name='2gis site code')),
                ('phone', models.CharField(blank=True, max_length=12, unique=True, validators=[account.models.validate_phone], verbose_name='Phone Number')),
                ('work_time_start', models.TimeField(default=django.utils.timezone.now, verbose_name='Work Time Start')),
                ('work_time_end', models.TimeField(default=django.utils.timezone.now, verbose_name='Work Time End')),
                ('return_time_start', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Time Return')),
                ('view_on_front', models.BooleanField(default=False, verbose_name='view on frontend')),
            ],
            options={
                'verbose_name': 'Ofice',
                'verbose_name_plural': 'Ofices',
            },
        ),
    ]
