# Generated by Django 3.0.3 on 2020-02-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_workstation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workstation',
            unique_together={('host', 'ip_address')},
        ),
    ]
