# Generated by Django 3.0.3 on 2020-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='../static/images/avatar/unnamed.jpg', upload_to='products/%Y/%m-%d', verbose_name='Image'),
        ),
    ]
