# Generated by Django 3.0.3 on 2020-02-28 05:08

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200227_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscategory',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='../static/images/noimage.png', upload_to='categories/%Y/%m-%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='servicescategory',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='../static/images/noimage.png', upload_to='categories/%Y/%m-%d', verbose_name='Image'),
        ),
    ]
