# Generated by Django 3.0.3 on 2020-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200228_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscategory',
            name='image',
            field=models.ImageField(default='../static/images/noimage.png', upload_to='categories/%Y/%m-%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='servicescategory',
            name='image',
            field=models.ImageField(default='../static/images/noimage.png', upload_to='categories/%Y/%m-%d', verbose_name='Image'),
        ),
    ]
