# Generated by Django 3.0.3 on 2020-02-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Products Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicescategory',
            options={'verbose_name': 'Service Category', 'verbose_name_plural': 'Services Categories'},
        ),
    ]
