# Generated by Django 3.0.3 on 2020-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200212_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscategory',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='url_slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='servicescategory',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicescategory',
            name='url_slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
