# Generated by Django 3.0.3 on 2020-02-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200212_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.IntegerField(choices=[(1, 'thing'), (2, 'meter'), (3, 'packaging')], default=1, verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Vendor Code'),
        ),
    ]
